<a href="https://colab.research.google.com/github/bonghyerim/my-study/blob/main/20230503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def add_all(*inputs):
    s=0
    for i in range(len(inputs)):
      s += inputs[i]
    return s

def add_all2(*inputs):
    return sum(inputs)

In [ ]:
add_all(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

55

In [ ]:
def add_all3(*args):
  s=0
  for i in args:
    for j in i:
      s += j
    return s

add_all3([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
def add_all4(*args):
  temp = 0
  for i in range(len(args)):
    if type(args[i]) == list:
      for j in args[i]:
        temp += j
    else :
      temp += args[i]
  return temp

In [ ]:
add_all4([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

55

In [ ]:
import numpy as np
print(np.__version__)

In [ ]:
A = [1,2,3,4]

a = np.array(A)
print(type(a))
print(a)

In [ ]:
import numpy as np
A = [1,2,3,4]
a = np.array(A)
s = a[:2]
print('A의 출력입니다.')

A의 출력입니다.


- Ndarray 타입을 검색하거나 슬라이싱은 참조만 할당하므로 변경을 방지하기 위해서는 새로운 Ndarray로 만들어 사용 .copy 메소드가 필요

In [ ]:
ss = a[:2].copy()
print(ss.size)
ss[0]=99
print(a)
print(s)
print(ss)

2
[1 2 3 4]
[1 2]
[99  2]


In [ ]:
type(A)

list

In [ ]:
a1 = np.asarray(A)
print(type(a1))
a1

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

- 벡터화
  - 배열은 for문을 작성하지 않고 데이터를 일괄 처리 하는 것

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

- 브로드캐스팅
  - 다른 모양의 배열 간의 산술 연산을 수행할 수 있도록 해주는 numpy의 기능

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
10-arr

array([[9, 8, 7],
       [6, 5, 4]])

In [ ]:
arr*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
arr/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [ ]:
arr2 = np.array([100,200,300])

In [ ]:
arr4 = np.array([[100],[200],[300]])

In [ ]:
arr+arr4

ValueError: ignored

In [ ]:
arr3 = np.array([100,200])

In [ ]:
arr+arr3

ValueError: ignored

In [ ]:
arr+arr2

array([[101, 202, 303],
       [104, 205, 306]])

- 요기까지 복습내용

In [ ]:
arr = np.zeros((3,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
arr.flatten() # 1D vector로 만드는 것

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.array([[1,2],[3,4]])
arr.flatten()

array([1, 2, 3, 4])

- reshape
  - 이미 존재하는 배열을 내가 원하는대로 shape를 조정을 함

In [ ]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr.reshape(3,4) # 주어진 shape의 약수로 이루어진 shape만 가능

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.reshape(4,3)
arr.reshape(1,12) # = flatten()
arr.reshape(12,1)
arr.reshape(2,6)
arr.reshape(6,2)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr= np.arange(20)

In [ ]:
arr.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr.reshape(5,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr.reshape(-1,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
arr.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr1 = np.arange(4).reshape(2,2)
arr1


array([[0, 1],
       [2, 3]])

In [ ]:
arr1.transpose()

array([[0, 2],
       [1, 3]])

In [ ]:
print(arr.transpose().shape)
arr.transpose()

(5, 4)


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A = [5, 23, 2, 1, 5]
A.sort()

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
A1 = [5, 23, 2, 1, 5]
sorted(A1)

[1, 2, 5, 5, 23]

In [ ]:
A1

[5, 23, 2, 1, 5]

In [ ]:
arr = np.arange(30).reshape(3,2,5)
arr.shape

(3, 2, 5)

In [ ]:
arr.transpose().shape

(5, 2, 3)

In [ ]:
arr.T

array([[[ 0, 10, 20],
        [ 5, 15, 25]],

       [[ 1, 11, 21],
        [ 6, 16, 26]],

       [[ 2, 12, 22],
        [ 7, 17, 27]],

       [[ 3, 13, 23],
        [ 8, 18, 28]],

       [[ 4, 14, 24],
        [ 9, 19, 29]]])

In [ ]:
x = np.arange(6).reshape(-1,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

## p.54 연습문제2)

In [ ]:
import numpy as np

arr = np.arange(0,21)
arr1= []
arr2= []
for i in arr:
  if arr[i] % 2 == 0 :
    arr1.append(arr[i])
  else :
    arr2.append(arr[i])

arr1


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
import numpy as np
Arr = np.arange(0,21)

Arr1 = Arr[Arr%2==0]
Arr2 = Arr[Arr%2!=0]



In [ ]:
arr1d = np.arange(8)
arr1d[1]

1

In [ ]:
arr1d[-1]

7

In [ ]:
arr1d[:4]

array([0, 1, 2, 3])

- 브로드 캐스팅

In [ ]:
lst = list(range(6))
lst

[0, 1, 2, 3, 4, 5]

In [ ]:
lst[2:5] = -1 #can only assign an iterable
lst

In [ ]:
lst[3] = -1
lst

[0, 1, 2, -1, 4, 5]

In [ ]:
arr1d = np.arange(8)
arr1d


array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr1d[3:6] = 100 # 슬라이싱해서 숫자 변경이 가능
arr1d

array([  0,   1,   2, 100, 100, 100,   6,   7])

- view

In [ ]:
arr2d = np.arange(20).reshape(4,-1)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr2d[0] # 첫 번째 행

array([0, 1, 2, 3, 4])

In [ ]:
arr2d[1][2] # 재귀적 접근 1행 2열

7

In [ ]:
arr2d[1,2] # 컴마를 이용하여 쉽게 인덱싱을 할 수 있음

7

In [ ]:
arr2d[:3,:2] # 행과 열을 접근하기 위해서는 컴마로 연결해야 함

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

- 불리안 배열
  - 불리안 값으로 이뤄진 배열

In [ ]:
arr= np.array([0,1,2,3,4])
arr[[True,False,True,False,True]]

array([0, 2, 4])

In [ ]:
arr2d = np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

- 멀티 인덱스

In [ ]:
arr2d[[0,2]] # 0행과 2행 # multi index는 [] 하나 더 추가해야 함.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [ ]:
arr2d[[0,3],[4]]

array([ 4, 19])

In [ ]:
arr2d[[0,1],[4,3]]

array([4, 8])

- 유니버셜 함수

In [ ]:
arr= np.arange(-3,3).reshape(3,-1)
arr

array([[-3, -2],
       [-1,  0],
       [ 1,  2]])

In [ ]:
np.exp(arr)

array([[0.04978707, 0.13533528],
       [0.36787944, 1.        ],
       [2.71828183, 7.3890561 ]])

In [ ]:
np.floor(arr)

array([[-3., -2.],
       [-1.,  0.],
       [ 1.,  2.]])

-  **이항 유니버셜**

In [ ]:
arr1 = np.arange(8).reshape(2,-1)
arr2 = np.arange(-40,40,10).reshape(2,-1)
print(arr1)
print(arr2)

[[0 1 2 3]
 [4 5 6 7]]
[[-40 -30 -20 -10]
 [  0  10  20  30]]


In [ ]:
np.maximum(arr1,arr2) # 같은 원소에서 가장 큰 값

array([[ 0,  1,  2,  3],
       [ 4, 10, 20, 30]])

In [ ]:
np.subtract(arr1,arr2) # 뺄셈

array([[ 40,  31,  22,  13],
       [  4,  -5, -14, -23]])

In [ ]:
np.multiply(arr1,arr2)  # 같은 원소끼리 곱셈

array([[  0, -30, -40, -30],
       [  0,  50, 120, 210]])

- 통계 메서드

In [ ]:
arr = np.arange(4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

In [ ]:
arr.sum()

6

In [ ]:
arr.sum(axis=0)

array([2, 4])

In [ ]:
arr.sum(axis=1)

array([1, 5])

In [ ]:
arr.mean()

1.5

In [ ]:
arr.mean(axis=0)

array([1., 2.])

In [ ]:
arr.mean(axis=1)

array([0.5, 2.5])

- where
  - x if 조건 else y의 벡터화 버전.
  - numpy를 사용하여 배열을 빠르게 처리할 수 있으며, 다차원도 간결하게 표현이 가능

In [ ]:
xarr = np.array([100,200,300,400])
yarr = np.array([1,2,3,4])
cond = np.array([True,False,True,False])

In [ ]:
result = np.where(cond,xarr,yarr)
result

array([100,   2, 300,   4])

In [ ]:
np.where(xarr>200,max(xarr),0)

array([  0,   0, 400, 400])

In [ ]:
np.where(xarr%3==0,1,0)

array([0, 0, 1, 0])

- sort()

In [ ]:
np.random.seed(42)
arr = np.random.randint(1, 100, size = 10) # 1~100까지의 정수 중에 10개를 뽑아주세요.
arr

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [ ]:
arr.sort()

In [ ]:
arr

array([15, 21, 52, 61, 72, 75, 75, 83, 87, 93])

In [ ]:
-np.sort(-arr)

array([93, 87, 83, 75, 75, 72, 61, 52, 21, 15])

- array의 sort에서는 내림차순, 오름차순을 선택하는 옵션이 없다

In [ ]:
lst = [1,32,4,1,20]
lst.sort(reverse=True)
lst

[32, 20, 4, 1, 1]

- 선형대수패키지

- 단위 행렬
  - 대각 원소 1이고, 나머지는 0인 n차 정발 행렬을 말하며, numpy의 eye() 함수를 사용하여서 만들 수 있음.

In [ ]:
import numpy as np
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
identity = np.eye(2,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]]


- 대각 행렬
  - 대각 성분 이외의 모든 성분이 모두 '0'인 n차 정발 행렬

In [ ]:
x = np.arange(9).reshape(3,-1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
np.diag(x)

array([0, 4, 8])

In [ ]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

- dot
  - 원소간의 곱(element-wise product)
  - 벡터의 내적(행렬의 곱)

In [ ]:
a = np.arange(4).reshape(-1,2)
print(a)

[[0 1]
 [2 3]]


In [ ]:
a * a

array([[0, 1],
       [4, 9]])

In [ ]:
np.multiply(a,a)

array([[0, 1],
       [4, 9]])

In [ ]:
np.dot(a,a)

array([[ 2,  3],
       [ 6, 11]])

In [ ]:
a.dot(a)

array([[ 2,  3],
       [ 6, 11]])

- matmul : matrix multiplication

In [ ]:
a = np.random.randint(-3,3,10).reshape(2,5)
b = np.random.randint(0,5,15).reshape(5,3)
a.shape, b.shape

((2, 5), (5, 3))

In [ ]:
ab = np.matmul(a,b)
print(ab.shape,'\n') #\n : 개행
print(ab)

(2, 3) 

[[  7  11   4]
 [ -2 -10  -2]]


In [ ]:
np.dot(a,b) # dot->1차원 벡터 공식문서에는 2D(2차원) matmul로 돌아감.

In [ ]:
!pip installl numpy
!pip installl pandas

ERROR: unknown command "installl" - maybe you meant "install"
ERROR: unknown command "installl" - maybe you meant "install"


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
obj = pd.Series([0,1,2,3,4,5,6,7], index=['a','b','c','d','e','f','g','h'],dtype='int64')

In [ ]:
obj

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [ ]:
obj[3]

3

In [ ]:
obj[[1,3,5]] # multi index 접근방법

b    1
d    3
f    5
dtype: int64

In [ ]:
obj[1:3]

b    1
c    2
dtype: int64

In [ ]:
obj[obj<3] #boolean indexing

a    0
b    1
c    2
dtype: int64

In [ ]:
obj[1:3]

b    1
c    2
dtype: int64

In [ ]:
obj


a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [ ]:
obj.c

2

In [ ]:
obj['c']

2

In [ ]:
obj[['e','c']]

e    4
c    2
dtype: int64

In [ ]:
obj['a':'d']

a    0
b    1
c    2
d    3
dtype: int64

In [ ]:
obj['d':'e']=100

In [ ]:
obj

a      0
b      1
c      2
d    100
e    100
f      5
g      6
h      7
dtype: int64

- integer location based (iloc)

In [ ]:
obj = pd.Series([0,1,2,3,4,5,6,7], index=['a','b','c','d','e','f','g','h'],dtype='int64')

In [ ]:
obj.iloc[2]

2

In [ ]:
obj.iloc[[2]]

In [ ]:
obj.iloc[1:4]

- location based

In [ ]:
obj.loc['a':'c']

In [ ]:
df = pd.DataFrame(np.arange(24).reshape(4,-1), columns=['c1','c2','c3','c4','c5','c6'],
                  index=['r1','r2','r3','r4'])

df

In [ ]:
df['c3']
df.c3

In [ ]:
df[['c1','c3']]

In [ ]:
df['r1':'r2']

In [ ]:
df['c1':'c2'] # 열중심이라서..? 방향을 바꾸지 못해서

- iloc

In [ ]:
df.iloc[[0],[3]]

In [ ]:
df.iloc[[0,1],1:4]

- loc

In [ ]:
df.loc[['r1'],['c4']]

In [ ]:
df.loc['r1':'r2',['c2','c3','c4']]

- 산술 연산자

In [ ]:
s1 = pd.Series([1,2,3,4], index=['a','b','c','d'])
s2 = pd.Series([10,20,30,40], index=['a','b','c','d'])
s1 + s2

In [ ]:
s1 = pd.Series([1,2,3,4], index=['a','b','c','d'])
s2 = pd.Series([10,20,30,40], index=['b','c','d','e'])
s1 + s2 #sql의 outer join

In [ ]:
s1.add(s2,fill_value=0)

In [ ]:
s2.add(s1,fill_value=0)

In [ ]:
import pandas as pd
stock = pd.read_csv('https://raw.githubusercontent.com/Youngpyoryu/Lecture_Note/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC/stock_2020_01.csv',encoding='CP949')

In [ ]:
stock = pd.read_csv('/content/stock_2020_01.csv',encoding='CP949')

In [ ]:
stock

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
stock = pd.read_csv('/content/drive/MyDrive/stock_2020_01.csv', encoding='CP949')
stock

In [ ]:
stock.head()  # 위에서 5개

In [ ]:
stock.head(3)

In [ ]:
stock.tail()

- 기술 통계량

In [ ]:
stock.describe() # median = 50% 평균하고 중앙값이 같은 거 정규분포 (중심에 대해서 대칭)

- 결측지(missing value)


In [ ]:
stock.isna().sum()
#stock.isnull().sum()

Date               0
kospi              0
kosdaq             0
gold_fut_132030    0
Bond_273130        0
dtype: int64

- 데이터의 자료형 -> info()

In [ ]:
stock.info()

In [ ]:
stock['Date']

In [ ]:
stock['kospi'].sort_values()

- unique
  - 중복되는 값을 제거하고 유일한 값만 담고 있는 Series를 반환

- nan : Not a number

In [ ]:
import numpy as np
obj = pd.Series([2,1,3,3,1,5,np.nan,1,2])
obj

0    2.0
1    1.0
2    3.0
3    3.0
4    1.0
5    5.0
6    NaN
7    1.0
8    2.0
dtype: float64

In [ ]:
obj.isnull().sum()

1

In [ ]:
obj.unique() #Series 밖에 안 됨 DataFrame에는 안 됨

array([ 2.,  1.,  3.,  5., nan])

- value_counts

In [ ]:
obj.value_counts()

1.0    3
2.0    2
3.0    2
5.0    1
dtype: int64

In [ ]:
obj.value_counts(normalize=True)

In [ ]:
obj = pd.Series([1,2,3,-1,-2], index=list('가마나라다'))
obj

가    1
마    2
나    3
라   -1
다   -2
dtype: int64

In [ ]:
obj.sort_index(ascending=False)

마    2
라   -1
다   -2
나    3
가    1
dtype: int64

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),index = list('abc'),columns = list('edf'))

frame

e  d  f
a  0  1  2
b  3  4  5
c  6  7  8

In [ ]:
frame.sort_index()

e  d  f
a  0  1  2
b  3  4  5
c  6  7  8

In [ ]:
frame.sort_index(axis=1)

d  e  f
a  1  0  2
b  4  3  5
c  7  6  8

In [ ]:
frame.sort_index(axis=1)

In [ ]:
frame

e    3.0
d    4.0
f    5.0
dtype: float64

In [ ]:
frame.sort_values(by='e', ascending=False)
frame.sort_values(by=['e','f'],ascending=[False,False])

e  d  f
c  6  7  8
b  3  4  5
a  0  1  2

- map
  - Series의 각각의 element들을 다른 어떤 값을 대체하는 역할

In [ ]:
series = pd.Series([100,200,300])
series

0    100
1    200
2    300
dtype: int64

In [ ]:
series.map({100:'C',200:'B',300:'A'})

0    C
1    B
2    A
dtype: object

In [ ]:
series.map('${}'.format)

0    $100
1    $200
2    $300
dtype: object

In [ ]:
series.map('{}달러'.format)

0    100달러
1    200달러
2    300달러
dtype: object

In [ ]:
f = lambda x: np.add(x,3)
series.map(f)

0    103
1    203
2    303
dtype: int64

- apply
  - map보다 적용할 수 있는 범위가 큰 것

In [ ]:
s = pd.Series([20,21,12], index=['London','New York','Helsinki'])
s

London      20
New York    21
Helsinki    12
dtype: int64

In [ ]:
def sub_custom_value(x,val):
    return x-val

In [ ]:
s.apply(sub_custom_value,args=(10,))

London      10
New York    11
Helsinki     2
dtype: int64

In [ ]:
def add_custom_values(x,**kwargs):
  for month in kwargs:
    x += kwargs[month]
  return x

In [ ]:
s.apply(add_custom_values, june=30, july=20, august=25)

London      95
New York    96
Helsinki    87
dtype: int64