<a href="https://colab.research.google.com/github/bonghyerim/my-study/blob/main/20230502.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def Sandwich(eggs):
  eggs.append(1) # 기존 객체의 주소값에 [1]추가
  eggs = [2, 3]

ham = [0]
Sandwich(ham)
print(ham) # [0, 1]
print(eggs)



- 3가지 전달 방식

In [ ]:
# 1번 함수
def swap_value(x, y):
  temp = x
  x = y
  y = temp

# 2번 함수
def swap_offset(offset_x, offset_y):
  temp = a[offset_x]
  a[offset_x] = a[offset_y]
  a[offset_y] = temp

# 3번 함수
def swap_reference(list, offset_x, offset_y):
  temp = list[offset_x]
  list[offset_x] = list[offset_y]
  list[offset_y] = temp

# 테스트
a = [1, 2, 3, 4, 5]
swap_value(a[1], a[2])
print(a) # [1, 2, 3, 4, 5] swap 발생 안 함
swap_offset(1, 2)
print(a) # [1, 3, 2, 4, 5] swap 발생
swap_reference(a, 1, 2)
print(a) # [1, 2, 3, 4, 5] swap 발생 안 함

P.225 연습문제

In [ ]:
def div3(a,b):
  if a < b:
    big = b
    small = a
  elif b < a:
    big = a
    small = b
  else:
    print('정수가 아닙니다.')
  if small == 0:
    print('0은 사용할 수 없습니다.')
  elif abs(big) < 0 or abs(small) < 0:
    print('정수를 입력해 주세요')
  else:
    q  = big // small
    r = big % small
    return(q, r)
  

In [ ]:
div3(0,5)

In [ ]:
div3(3,5)

In [ ]:
div3(10,1)

P.229) 연습문제

In [ ]:
def func(string, unit=2):
  i = 0
  while i<len(string):
    print(string[i:i+unit])
    i += unit

func('테스트를 위한 문장입니다')

In [ ]:
def test(*args):
  print(args)

In [ ]:
test

<function __main__.test(*args)>

In [ ]:
test([1, 2],3)

In [ ]:
test([1, 2])

In [ ]:
def test2(**kwargs):
  print(kwargs)

In [ ]:
test2(a=1, b=2, c=3)

In [ ]:
def add_all(*inputs):
    s=0
    for i in range(len(inputs)):
      s += inputs
    return s

In [ ]:
def add_all2(*inputs):
    return sum

In [ ]:
add_all([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
def add_all3(*args):
  s=0
  for i in args:
    for j in i:
      s += j
    return s

In [ ]:
add_all3([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
def add_all4(*args):
  temp = 0
  for i in range(len(args)):
    if type(args[i]) == list:
      for j in args[i]:
        temp += j
    else :
      temp += args[i]
  return temp

In [ ]:
add_all4([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

- 팩토리얼을 구하시오.

In [ ]:
# 재귀적으로 하지 않은 것
def fant(n):
  f=1 #곱을 계산할 변수의 초깃값
  for i in range(1, n+1): #1부터 n까지 반복
    f = f*i #곱셈 연산
  return f

In [ ]:
# 재귀적으로 하는 것.
def fact(n):
  if n <= 1: #n 이 1 이하이면 종료조건
    return 1
  return n * fact(n-1)

In [ ]:
fact(5)

P.242

In [ ]:
people = ['펭수', '뽀로로', '뚝딱이', '텔레토비']

def func1(line):
  new_lines = []
  i = 1 #대기번호를 트래킹하는 변수 i
  for x in line:
    print('대기번호 %d 번 : %s' %(i,x))
    new_lines.append((i,x))
    i += 1 #별도로 업데이트를 해줘야 함.
  return new_lines

In [ ]:
line = func1(people)

- enumerate(열거하다)
  - 반복 가능한 객체의 인덱스와 원소에 함께 접근할 수 있는 함수

In [ ]:
lst = ['a','b','c']
for x in enumerate(lst):
  print(x)

lst1 = 'abcd'
for x in enumerate(lst1):
  print(x)

In [ ]:
people = ['펭수', '뽀로로', '뚝딱이', '텔레토비']

def func1(line):
  new_lines = []
  for idx,val in enumerate(line):
    print('대기번호 %d 번 : %s' %(idx, val))
    new_lines.append((idx+1, val))
  return new_lines

In [ ]:
line = func1(people)

대기번호 0 번 : 펭수
대기번호 1 번 : 뽀로로
대기번호 2 번 : 뚝딱이
대기번호 3 번 : 텔레토비


- zip
  - 반복 가능한 객체들을 (2개 이상) 병렬적으로 묶어주는 함수
  - 각 원소들을 튜플의 형식으로 묶어줌

In [ ]:
str_list = ['one','two','three','four']
num_list = [1, 2, 3, 4]

for i in zip(num_list, str_list):
  print(i)

(1, 'one')
(2, 'two')
(3, 'three')
(4, 'four')


- lambda
  - 한 줄을 실행한 결과 값이 바로 반환이 됨

In [ ]:
def plus_two(num) :
  return num + 2

In [ ]:
a = 2
b = plus_two(a)
print(b)

In [ ]:
lambda x : x + 2  # 람다는 함수를 생성함

In [ ]:
func2 = lambda x : x + 2

c = func2(2)
c

In [ ]:
items = [1, 2, 3, 4, 5]

squared = []
for i in items :
  squared.append(i*i)

print(squared)

In [ ]:
squared_map = list(map(lambda x : x**2, items))
print(squared_map)

In [ ]:
items=[1, 24, 3, 6, 7]
str_items = list(map(lambda x : str(x), items))

print(str_items)

- list comprehension



- 0~9까지 순서대로 가지고 있는 리스트를 만드세요.

In [ ]:
#1. 
list_1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#2.
list_2 = []
for x in range(10):
  list_2.append(x)
print(list_2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
lc_1 = [x for x in range(10)]
print(lc_1)



In [ ]:
tables = [2 *x for x in range(1, 10)]
print(tables)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
#2) 코로나 바이러스
sentence = '코로나 바이러스를 예방하기 위해 사회적 거리두기를 실천합시다. 마스크를 끼고 손씻기를 생활화 합시다.'

len_sent = [len(s) for s in sentence.split()]
print(len_sent)

[3, 5, 4, 2, 3, 5, 6, 4, 2, 4, 3, 4]


p. 258
- for문 + if문
  - 10부터 20까지의 숫자들 중에서 짝수만을 담은 리스트를 만들어보자

In [ ]:
list3 = []
for x in range(10,21):
  if x % 2 == 0:
    list3.append(x)
print(list3)

lc_2 = [x for x in range(10,21) if x % 2 ==0]
print(lc_2)

In [ ]:
#1)

lc_3 = [x for x in range(1,11) if x ** 2 <= 50]

print(lc_3)

#2)
lc_4 = [s for s in sentence.split() if len(s) < 5]
print(lc_4)

[1, 2, 3, 4, 5, 6, 7]
['코로나', '예방하기', '위해', '사회적', '마스크를', '끼고', '손씻기를', '생활화', '합시다.']


- for + if + else
  - 1부터 10까지의 숫자들 중 홀수이면 어떤 제곱수를, 짝수이면 세 제곱 수를 담은 리스트를 만들어보자

In [ ]:
list_4 = []
for x in range(1, 11):
  if x % 2 == 1:
    list_4.append(x ** 2)
  else :
    list_4.append(x ** 3)

list_4

[1, 8, 9, 64, 25, 216, 49, 512, 81, 1000]

In [ ]:
[x **2 if x % 2 == 0 else x ** 3 for x in range(1, 11)]

# 조건이 2 개이면 앞으로 튕겨가야 한다?

[1, 4, 27, 16, 125, 36, 343, 64, 729, 100]

In [ ]:
word_1 = 'Hello'
word_2 = 'World'

result = [i+j for i in word_1 for j in word_2]
result

In [ ]:
# 40 이하의 숫자는 5를 더하고 40초과의 숫자는 41로 바꾸어 리스트로 저장하고, 리스트로 출력하라

# 저장할 값 if 조건 else 저장할 값 for 원소 in 반복가능한 객체

list_5 = [12, 67, 32, 48, 19, 57, 29, 49]
lc_6 = [x+5 if x <=40 else 41 for x in list_5]
lc_6

[17, 41, 37, 41, 24, 41, 34, 41]

In [ ]:
students = {"보라돌이":61, "뚜비":35, "나나":78, "뽀":88}

result = [(name,True) if score > 60 else (name, False) for name,score in students.items()]
result

[('보라돌이', True), ('뚜비', False), ('나나', True), ('뽀', True)]

In [ ]:
import numpy as np

n=1000000
numpy_arr = np.arange(n)
python_list = list(range(n))

In [ ]:
%%time
#jupy notebook
python_list = [x**3+10 for x in python_list]

CPU times: user 364 ms, sys: 27.4 ms, total: 391 ms
Wall time: 395 ms


In [ ]:
%%time
numpy_arr = numpy_arr**3+10

CPU times: user 10.7 ms, sys: 3.27 ms, total: 14 ms
Wall time: 23.9 ms


In [ ]:
A = [1, 2, 3, 4]

a = np.array(A, np.int)
print(type(a))
print(a)            

<class 'numpy.ndarray'>
[1 2 3 4]


<ipython-input-152-15ac1bea8b15>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.array(A, np.int)


- 벡터화
  - 배열은 for문을 작성하지 않고 데이터를 일괄처리 하는 것

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

In [ ]:
arr + arr

In [ ]:
arr / arr

- 브로드캐스팅
  - 다른 모양의 배열 간의 산술 연산을 수행할 수 있도록 해주는 numpy의 기능

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
10-arr

array([[9, 8, 7],
       [6, 5, 4]])

In [ ]:
arr*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
arr2 = np.array([100,200,300])

In [ ]:
arr4 = np.array([[100],[200]])
arr4
arr+arr4

array([[101, 102, 103],
       [204, 205, 206]])

In [ ]:
arr3=np.array([100,200])

In [ ]:
arr+arr3

In [ ]:
list_1 = [1,2,3]
arr_1 = np.array([1,2,3])
arr_1+arr_1

array([2, 4, 6])

- dtype
  - 배열에 담긴 원소의 자료형(ndarray는 같은 자료형을 담음)

In [ ]:
arr.dtype

dtype('int64')

- size
  - 배열에 있는 원소의 전체 갯수

In [ ]:
arr.size

6

- ndim
  - 배열의 차원 갯수

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

- 0차원(상수)

In [ ]:
import numpy as np
a = np.array(10)
print(a)
print(a.ndim)

10
0


- 1차원

In [ ]:
a = np.array([1,2,3])
print(a)
print(a.ndim)

[1 2 3]
1


- 2차원

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.ndim)

[[1 2]
 [3 4]]
2


- 3차원

In [ ]:
a = np.array([[[1,2],[3,4]]])
print(a)
print(a.ndim)
print(a.shape)

[[[1 2]
  [3 4]]]
3
(1, 2, 2)


- range 함수를 이용

In [ ]:
arr1 = np.array(range(20))
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

- zeros

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(-3,3)

array([-3, -2, -1,  0,  1,  2])

In [ ]:
np.arange(3,50,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [ ]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

-배열 결합 함수.
 - hstack, concatenate(axis=0)
 - 두 배열을 왼쪽에서 오른쪽으로 붙이기.

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

- vstack(vertical), concatenate(axis = 1)

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack([a,b])

In [ ]:
np.concatenate((a,b),axis=1) #1D vector는 안됨

In [ ]:
c = np.array([[0,1,2],[3,4,5]])
d = np.array([[6,7,8],[9,10,11]])
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

- 두 배열을 위 아래로 붙이기

In [ ]:
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [ ]:
np.column_stack([a,b])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
import random
import numpy as np

In [ ]:
random.random() # 0<=리턴값<=1

0.11753679814057993

In [ ]:
date = [1,2,3,4,5,6,7]
np.random.choice(date,3)

array([1, 6, 2])

In [ ]:
data = ['apple','banana','grape','orange']
random.choice(data)

'apple'

- seed
  - 난수 초기값 부여 -> 재현 가능성(reproducibility)

In [ ]:
np.random.seed(42)

In [ ]:
np.random.rand(1000) # 정규분포

In [ ]:
date = range(1,46)
d= np.random.choice(date,6)

n = int(input(('로또 번호를 몇 개 생성할까요? > ')))

for i in range(n):
  print("로또 번호 :",d)
  


로또 번호를 몇 개 생성할까요? > 7
로또 번호 : [45 32 37 30 45 43]
로또 번호 : [45 32 37 30 45 43]
로또 번호 : [45 32 37 30 45 43]
로또 번호 : [45 32 37 30 45 43]
로또 번호 : [45 32 37 30 45 43]
로또 번호 : [45 32 37 30 45 43]
로또 번호 : [45 32 37 30 45 43]


In [ ]:
import numpy as np
def make_lotto(count):
  for i in range(count):
    lotto_num = [] # 로또 번호가 담길 리스트 함수
    for j in range(6):
      lotto_num = np.random.choice(range(1,46),6,replace=False) #중복 추출
      lotto_num.sort() # 값 정렬
    print('{},로또번호:{}'.format(i+1,lotto_num))

In [ ]:
count = int(input('로또 번호를 몇 개 생성할까요?'))
make_lotto(count)

로또 번호를 몇 개 생성할까요?4
1,로또번호:[ 4 16 17 24 31 42]
2,로또번호:[22 27 29 35 37 38]
3,로또번호:[15 17 21 30 34 45]
4,로또번호:[14 17 18 30 36 44]
